### ISSUE TITLE
Resolving page

### ISSUE THREAD

**Issue by contextlimit** [phproad/phproad#2]
1) I personally don't like how it will render the home page for 404's if there is no /404 page. At least it should throw the 404 header so it's not telling SE's it's legitimate.

2) $page is always null to start, so this ternary is redundant: https://github.com/phproad/phproad/blob/master/controllers/application.php#L13

3) We could let admins know they need to create a /404 page if they are signed in and one does not exist.

Proposed resolve_page:

``` php
    protected function resolve_page(&$params)
    {
        $params = null;
        $action = strtolower(Phpr::$request->get_current_uri());

        $page = Cms_Page::get_url($action, $params);

        if (!$page)
        {
            header("HTTP/1.0 404 Not Found");

            $page = Cms_Page::get_url('/404', $params);

            if (!$page)
                die(Phpr::$security->get_user() ? "That page could not be found. You should create a /404 page for unfound pages." : "Sorry, that page could not be found.");
        }

        return $page;
    }
```

**Comment by daftspunk** [comment]
+1 
Do it.

Also suggest maybe additionally using
`Cms_Page::get_url_from_action('cms:404')`

This way it would look for the first page with the page action **cms:404** instead of forcing a given URI

Just throwing it out there ;-)

**Comment by contextlimit** [comment]
Still love what we built here but gotta clean up my open issues~
