### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Garbee** [phproad/phproad#3]
So, we obviously need documentation for PHPRoad. Doing inline documentation though is a PITA to build out. I am personally thinking that we should simply have really good documentation for people to get going with the system on the site under /docs. All hand-written an external from the source. Then for people who _really_ want detailed docs, we can somehow host Doxygen output (probably on a sub-domain) for that. It auto-generates an awesome setup for detailed docs. We can have a hook automatically run doxygen on new code being pushed to master (or however things get sent to users.) 

Any issues with this kind of setup for docs?

**Comment by contextlimit** [comment]
We're looking at documenting everything here in this Github Wiki as we develop out our apps, full of as much info and examples as we can. Then we will link to these wiki pages from the class/function meta comment. As you use/improve PHPR, please go nuts Garbee, adding as much information as you can for every single thing, in the wiki :+1:
