### ISSUE TITLE
In the hands of the people, on PHPR's short-tags.

### ISSUE THREAD

**Issue by webdeli** [phproad/phproad#5]
I believe that any future user / developer will be more delighted by the experience of having PHPR work out of the gates.

Presently the use of short-tag format PHP necessitates the bulk of users with a default PHP config to first go change this to get to step zero (pre-install check).

While short-tags '<?' save 3 characters over '<?php' that does not seem to be any great advance in utility to the PHPR core developers and contributors while it does come at a material cost to new users forced to get under the hood of their PHP config just to on-board.

We don't live in a keystroke world of development, generally we are in IDE land, autocompletopia and snippetville to boot.

I propose PHPR abandon the use of short_tags '<?' in order to smooth out the adoption grade.

**Comment by contextlimit** [comment]
Please no. Even though I agree with the first statement. No short tags is
cumbersome to type, but more importantly to read. Read code and
understanding logic, even our own, is more important. It works out of the
gate on Ubuntu. Short tags are enabled by default. If we're going to pursue
this, lets get some actual numbers on short_tag support. This is a waste of
effort in my opinion. We did just fine, no complaints someone couldn't
understand to enable or didn't already have enabled, in 3 years.

**Comment by webdeli** [comment]
Well take this as a complaint if you like, that is - a new to PHPR user.. I would be quick to point out that many of us use OS X for our development platform as oppose to Ubuntu. In Apple land the PHP has short_tags off by default.
1. There was a useful reference to this link circulated earlier: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md advocating the change.
2. As for short tags being on - From PHP.net: http://www.php.net/manual/en/ini.core.php#ini.short-open-tag would indicate that contrary to the Ubuntu experience the broader experience with PHP more generally is that "<?" is required to be enabled by the user. Or said another way: <? does't work by default.

To that end - given the agreed value of 'working out of the gates' - It's hard to argue that '<?php' tags are either sufficiently daunting to a core contributor / module developer nor does the terse nature of a self-declarative / self-descriptive and semantic nature of the '<?php' tag degrade readability or legibility. I would actually argue that it is the epitome of something being legible and descriptive while doing one and just one thing.

A '<?php' tag has little by way of alternate interoperation or affordance. It is in it's pure form the right code for the job.

Rather than this being constructed as a contest of wills however.. Eric would you look a little to the motivation for my request and the good faith nature it is being put forward in. Does the potential change damage your code practices a greater amount than the value the change affords to new users in the future?

**Comment by contextlimit** [comment]
Right, sorry. short_tags is disabled by default. The .htaccess and php.ini overloads work fine on Ubuntu and Mac though, right?

I don't have time to comment on this right now.

**Comment by Garbee** [comment]
@webdeli short_open_tags are _enabled_ by default with PHP. In the table just above where you linked to it clearly states the default value is "1". When did boolean logic change to make 1 = off?

There is no real point in switching the entire codebase over just to facilitate a non-issue. How many people will be tripped by not having short_open_tags on? Further, how hard is it to turn on? No difficult and not many will have an issue. If someone does, we can easily walk them through configuring their system.

UPDATE: Further on the fig standards... We obviously aren't following them. We use tabs vs spaces, our naming convention is different for classes, no namespacing support built into the system (although they can be used if you wish), etc. So why conform to this one thing? FIG standards mean nothing to PHPRoad, period.

**Comment by daftspunk** [comment]
PHP short tags are staying. They now come as standard in PHP 5.4.
