### ISSUE TITLE
License key unobtainable

### ISSUE THREAD

**Issue by damanic** [phproad/phproad#7]
http://phproad.com/register/
Is not working. Presumed avenue for obtaining a license key.

Installer is not allowing keyless installs.

Result, phproad not currently usable?

**Comment by daftspunk** [comment]
Registration is disabled at the moment.

Jump on irc.freenode.net #phpr to discuss.

**Comment by damanic** [comment]
Hi m8,  I cant log in to my account on phproad.com that you set up for me. I no longer have the zoot@ email address it was issued to. I've not seen you on #Phpr recently ...   Could you email me at spam2014@mjman.net so I can give you details to restore my account. 

Cheers.
