### ISSUE TITLE
Using/installing phproad

### ISSUE THREAD

**Issue by ghost** [phproad/phproad#8]
How does one go about installing/use phproad it appears self installation is licensed and one can't obtain license. Direct clone and run produces this error/404 page 

/Users/O/Documents/Development/web/other/phpr/core/init.php Sorry, the file you were looking for could not be found. 

Just need quick guide to get it working

**Comment by Garbee** [comment]
Hop into freenode IRC (irc.freenode.net) and head into the #phpr channel. Then speak with daftspunk when he is around (Australian time) to get an account to the site so you can generate keys.

Cloning this repo also won't help at all, you need to go through the installer to have everything working properly.

**Comment by omarkassim** [comment]
@Garbee @daftspunk Hey guys! I was wondering if it may be possible to get a key to install PHPRoad? The #phpr channel does not seem to be active at the moment.

**Comment by daftspunk** [comment]
Hey @omarkassim Try in #october instead, this is the 2nd gen PHPR.
You can also find more on the project here: [October CMS](https://github.com/octobercms/)

**Comment by omarkassim** [comment]
@daftspunk Thanks! Will try to reach you there. October looks interesting, would still like a play with PHPRoad if possible. Will explain on IRC.
